<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Eplan.EplApi.AFu">
      <HintPath>..\DLLs\Eplan.EplApi.AFu.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Eplan.EplApi.Baseu">
      <HintPath>..\DLLs\Eplan.EplApi.Baseu.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Eplan.EplApi.DataModelu">
      <HintPath>..\DLLs\Eplan.EplApi.DataModelu.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Eplan.EplApi.Guiu">
      <HintPath>..\DLLs\Eplan.EplApi.Guiu.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Eplan.EplApi.HEServicesu">
      <HintPath>..\DLLs\Eplan.EplApi.HEServicesu.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Eplan.EplApi.MasterDatau">
      <HintPath>..\DLLs\Eplan.EplApi.MasterDatau.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="Eplan.EplApi.Starteru">
      <HintPath>..\DLLs\Eplan.EplApi.Starteru.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Eplan.EplApi.Systemu">
      <HintPath>..\DLLs\Eplan.EplApi.Systemu.dll</HintPath>
      <Private>True</Private>
    </Reference>
  </ItemGroup>

</Project>
